 void color(int couleurDuTEXTE,int couleurDeFond);
 void  co (int i);
 int score(int joueur);
 void congratus(int joueur);
 int score(int joueur);
 int Somme_Etat(int joueur);
 void grille();
 void MOULIN(int i,int j,int u,int joueur);
 void TRAITEMENT(int joueur);
 void tr_double_moulin(int joueur,int adv);
 int  VOISINAGE_double_moulin(int a,int b,int c,int d,int joueur);
 void double_moulin(int joueur,int m);
 void remplissage_joueur(int joueur);
 int verification_blocage(int i);
 int blocage(int joueur);
 void remplissage();
 void traitement_deplacement(int* a,int joueur );
 void deplacement(int joueur );
 void VOLE(int joueur);
 void RANKING1();
 int  test_fin(int joueur,int adv);
 void JvsJ();
 void Traitement_moulin_ordi(int*n);
 void MOULIN_ORDI(int i,int j,int u);
 void TRAITMENT_ORDINATEUR();
 void tr_double_moulin_ordi();
 void double_moulin_ordi(int m);
 void remplissage_machine();
 void traitement_deplacement_machine(int*a);
 void deplacement_machine();
 void VOLE_MACHINE();
 void lost();
 int test_fin_M();
 void HvsM();
 int verify(int a,int b,int c,int nbr);
 int AI(int nbr);
 void remplissage_machine_AI();
 int DEPLAC_AI(int a,int b,int av,int v);
 void TR_D_AI(int a,int b,int av,int v);
 void Deplacement_AI();
 void HvsAI();
